[package]
name = "modular-mc"
authors = ["ModularMC Team"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dashmap = "5"

[dependencies.bevy]
version = "0.6"
default-features = false
features = [ "trace" ]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
