name: ModularMC Extremely Overcomplicated Build Script!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      
      - uses: actions-rs/cargo@v1
        with:
          command: test
    
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: true
          - os: windows-2022
            target: x86_64-pc-windows-msvc
            cross: false
            
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - uses: Swatinem/rust-cache@v1
      with:
          sharedKey: ${{ matrix.target }}
          
    - uses: actions-rs/cargo@v1
      with:
          use-cross: ${{ matrix.use-cross }}
          command: build
          args: --target=${{ matrix.target }}
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ModularMC-Server
        path: |
          target/release/ModularMC
          target/release/ModularMC.exe
