name: ModularMC Extremely Overcomplicated Build Script!

on:
  push:
    branches: [ Dev ]
  pull_request:
    branches: [ Dev ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: cargo test --verbose 
    
  Build-Linux:
    name: Build-Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - uses: Swatinem/rust-cache@v1
      with:
          sharedKey: ${{ runner.os }}
    - run: cargo build --release
