name: ModularMC Extremely Overcomplicated Build Script!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      
      - run: cargo test --verbose 
    
  Build-Windows:
    name: Build-Windows
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - uses: Swatinem/rust-cache@v1
      with:
          sharedKey: ${{ runner.os }}
    - run: cargo build --release
  
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: ModularMC-Server
        path: target/release/ModularMC.exe


  Build-Linux:
    name: Build-Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
    - uses: Swatinem/rust-cache@v1
      with:
          sharedKey: ${{ runner.os }}
    - run: cargo build --release
  
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: ModularMC-Server
        path: target/release/ModularMC
